# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.12.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.filemanager_managed_file import FilemanagerManagedFile

class TestFilemanagerManagedFile(unittest.TestCase):
    """FilemanagerManagedFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilemanagerManagedFile:
        """Test FilemanagerManagedFile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilemanagerManagedFile`
        """
        model = FilemanagerManagedFile()
        if include_optional:
            return FilemanagerManagedFile(
                file_name = '',
                file_size = 56,
                local_file_path = '',
                meta_data = {
                    'key' : None
                    },
                mimetype = '',
                processing_errors = [
                    ''
                    ],
                url = ''
            )
        else:
            return FilemanagerManagedFile(
        )
        """

    def testFilemanagerManagedFile(self):
        """Test FilemanagerManagedFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
