# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.14.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.file_upload_response import FileUploadResponse

class TestFileUploadResponse(unittest.TestCase):
    """FileUploadResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileUploadResponse:
        """Test FileUploadResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileUploadResponse`
        """
        model = FileUploadResponse()
        if include_optional:
            return FileUploadResponse(
                incoming_file_name = '',
                processing_error = '',
                resulting_files = [
                    aigentchat.models.filemanager/processing_result_file.filemanager.ProcessingResultFile(
                        file_name = '', 
                        file_size = 56, 
                        local_file_path = '', 
                        mime_type = '', 
                        url = '', )
                    ]
            )
        else:
            return FileUploadResponse(
        )
        """

    def testFileUploadResponse(self):
        """Test FileUploadResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
