# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.18.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.api.connection_tokens_api import ConnectionTokensApi


class TestConnectionTokensApi(unittest.TestCase):
    """ConnectionTokensApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConnectionTokensApi()

    def tearDown(self) -> None:
        pass

    def test_create_connection_token_handler(self) -> None:
        """Test case for create_connection_token_handler

        Create a connection token for SSE
        """
        pass


if __name__ == '__main__':
    unittest.main()
