# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.12.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.api.execution_logs_api import ExecutionLogsApi


class TestExecutionLogsApi(unittest.TestCase):
    """ExecutionLogsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExecutionLogsApi()

    def tearDown(self) -> None:
        pass

    def test_get_execution_logs_costs(self) -> None:
        """Test case for get_execution_logs_costs

        Get execution logs costs
        """
        pass

    def test_search_execution_logs(self) -> None:
        """Test case for search_execution_logs

        Search execution logs
        """
        pass


if __name__ == '__main__':
    unittest.main()
