# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.14.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.api.agent_team_api import AgentTeamApi


class TestAgentTeamApi(unittest.TestCase):
    """AgentTeamApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AgentTeamApi()

    def tearDown(self) -> None:
        pass

    def test_add_agent_to_team(self) -> None:
        """Test case for add_agent_to_team

        Add an agent to a team
        """
        pass

    def test_create_agent_team(self) -> None:
        """Test case for create_agent_team

        Create a new agent team
        """
        pass

    def test_delete_agent_team(self) -> None:
        """Test case for delete_agent_team

        Delete an agent team
        """
        pass

    def test_get_agent_team(self) -> None:
        """Test case for get_agent_team

        Get an agent team
        """
        pass

    def test_get_full_agent_team(self) -> None:
        """Test case for get_full_agent_team

        Get a full agent team
        """
        pass

    def test_list_agent_teams(self) -> None:
        """Test case for list_agent_teams

        List agent teams
        """
        pass

    def test_remove_agent_from_team(self) -> None:
        """Test case for remove_agent_from_team

        Remove an agent from a team
        """
        pass

    def test_update_agent_team(self) -> None:
        """Test case for update_agent_team

        Update an agent team
        """
        pass

    def test_update_system_messages(self) -> None:
        """Test case for update_system_messages

        Update system messages
        """
        pass

    def test_update_user_messages(self) -> None:
        """Test case for update_user_messages

        Update user messages
        """
        pass


if __name__ == '__main__':
    unittest.main()
