# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.12.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.api.audio_api import AudioApi


class TestAudioApi(unittest.TestCase):
    """AudioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AudioApi()

    def tearDown(self) -> None:
        pass

    def test_create_audio_transcription(self) -> None:
        """Test case for create_audio_transcription

        Transcribe speech to text
        """
        pass

    def test_create_text_to_speech(self) -> None:
        """Test case for create_text_to_speech

        Text-To-Speech
        """
        pass


if __name__ == '__main__':
    unittest.main()
