# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.12.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.ai_model_capability import AIModelCapability

class TestAIModelCapability(unittest.TestCase):
    """AIModelCapability unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAIModelCapability(self):
        """Test AIModelCapability"""
        # inst = AIModelCapability()

if __name__ == '__main__':
    unittest.main()
