# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.18.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.org_cost_budget import OrgCostBudget

class TestOrgCostBudget(unittest.TestCase):
    """OrgCostBudget unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrgCostBudget:
        """Test OrgCostBudget
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrgCostBudget`
        """
        model = OrgCostBudget()
        if include_optional:
            return OrgCostBudget(
                org_id = '0',
                remaining_budget = 0,
                total_budget = 0,
                updated_at = 56,
                updated_by = '',
                used_budget = 0
            )
        else:
            return OrgCostBudget(
                org_id = '0',
        )
        """

    def testOrgCostBudget(self):
        """Test OrgCostBudget"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
