# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.15.9
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.agent_prompt_rendered_dto import AgentPromptRenderedDto

class TestAgentPromptRenderedDto(unittest.TestCase):
    """AgentPromptRenderedDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentPromptRenderedDto:
        """Test AgentPromptRenderedDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentPromptRenderedDto`
        """
        model = AgentPromptRenderedDto()
        if include_optional:
            return AgentPromptRenderedDto(
                rendered_prompt = ''
            )
        else:
            return AgentPromptRenderedDto(
        )
        """

    def testAgentPromptRenderedDto(self):
        """Test AgentPromptRenderedDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
