# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.15.9
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.token_direction import TokenDirection

class TestTokenDirection(unittest.TestCase):
    """TokenDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenDirection(self):
        """Test TokenDirection"""
        # inst = TokenDirection()

if __name__ == '__main__':
    unittest.main()
