# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.12.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.agent_team import AgentTeam

class TestAgentTeam(unittest.TestCase):
    """AgentTeam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentTeam:
        """Test AgentTeam
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentTeam`
        """
        model = AgentTeam()
        if include_optional:
            return AgentTeam(
                agent_ids = [
                    ''
                    ],
                coordinating_agent_id = '0',
                created_at = 56,
                description = '',
                id = '0',
                initial_user_messages = [
                    ''
                    ],
                initial_user_messages_mode = 'append',
                meta_data = None,
                name = '0',
                owner_id = '0',
                owner_organization_id = '0',
                system_messages = [
                    ''
                    ],
                system_messages_mode = 'append',
                tags = [
                    ''
                    ],
                updated_at = 56,
                updated_by = '0'
            )
        else:
            return AgentTeam(
                id = '0',
                name = '0',
                owner_id = '0',
                owner_organization_id = '0',
        )
        """

    def testAgentTeam(self):
        """Test AgentTeam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
