# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.6.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.organization_api_key_post_request import OrganizationApiKeyPostRequest

class TestOrganizationApiKeyPostRequest(unittest.TestCase):
    """OrganizationApiKeyPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationApiKeyPostRequest:
        """Test OrganizationApiKeyPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationApiKeyPostRequest`
        """
        model = OrganizationApiKeyPostRequest()
        if include_optional:
            return OrganizationApiKeyPostRequest(
                name = '0',
                organization_role_id = '',
                role_ids = [
                    ''
                    ],
                team_ids = [
                    ''
                    ],
                user_email = '',
                user_full_name = '0',
                user_name = '0'
            )
        else:
            return OrganizationApiKeyPostRequest(
                name = '0',
                user_email = '',
                user_full_name = '0',
                user_name = '0',
        )
        """

    def testOrganizationApiKeyPostRequest(self):
        """Test OrganizationApiKeyPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
