# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.5.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.agent_filter_options import AgentFilterOptions

class TestAgentFilterOptions(unittest.TestCase):
    """AgentFilterOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentFilterOptions:
        """Test AgentFilterOptions
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentFilterOptions`
        """
        model = AgentFilterOptions()
        if include_optional:
            return AgentFilterOptions(
                add_predefined_agents = True,
                model_ids = [
                    ''
                    ],
                q = '',
                tag_ids = [
                    ''
                    ],
                visibility = ''
            )
        else:
            return AgentFilterOptions(
        )
        """

    def testAgentFilterOptions(self):
        """Test AgentFilterOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
