# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.organization_credits_payment_response import OrganizationCreditsPaymentResponse

class TestOrganizationCreditsPaymentResponse(unittest.TestCase):
    """OrganizationCreditsPaymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationCreditsPaymentResponse:
        """Test OrganizationCreditsPaymentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationCreditsPaymentResponse`
        """
        model = OrganizationCreditsPaymentResponse()
        if include_optional:
            return OrganizationCreditsPaymentResponse(
                created_at = '',
                credits = 1.337,
                credits_budget_updated = True,
                currency = '',
                id = '',
                name = '',
                organization_id = '',
                total_amount = 56,
                updated_at = ''
            )
        else:
            return OrganizationCreditsPaymentResponse(
                created_at = '',
                credits = 1.337,
                credits_budget_updated = True,
                currency = '',
                id = '',
                name = '',
                organization_id = '',
                total_amount = 56,
                updated_at = '',
        )
        """

    def testOrganizationCreditsPaymentResponse(self):
        """Test OrganizationCreditsPaymentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
