# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.5.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.api.organizations_api import OrganizationsApi


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationsApi()

    def tearDown(self) -> None:
        pass

    def test_accept_invite(self) -> None:
        """Test case for accept_invite

        Accept Organization Invite
        """
        pass

    def test_create_member(self) -> None:
        """Test case for create_member

        Create a member for an Organization
        """
        pass

    def test_create_organization(self) -> None:
        """Test case for create_organization

        Create an Organization
        """
        pass

    def test_create_organization_api_key(self) -> None:
        """Test case for create_organization_api_key

        Create an api key for an Organization
        """
        pass

    def test_create_organization_role(self) -> None:
        """Test case for create_organization_role

        Create a role for an Organization
        """
        pass

    def test_create_subscription(self) -> None:
        """Test case for create_subscription

        Create a subscription for an Organization
        """
        pass

    def test_create_team(self) -> None:
        """Test case for create_team

        Create a team for an Organization
        """
        pass

    def test_create_team_member(self) -> None:
        """Test case for create_team_member

        Add a member to a team
        """
        pass

    def test_create_vaud_credits_payment(self) -> None:
        """Test case for create_vaud_credits_payment

        Create a vaud credits payment for an organization with active subscription
        """
        pass

    def test_delete_invite(self) -> None:
        """Test case for delete_invite

        Delete Organization Invite by ID
        """
        pass

    def test_delete_member(self) -> None:
        """Test case for delete_member

        Delete a member for an Organization
        """
        pass

    def test_delete_organization(self) -> None:
        """Test case for delete_organization

        Delete Organization by ID
        """
        pass

    def test_delete_organization_api_key(self) -> None:
        """Test case for delete_organization_api_key

        Delete an api key for an Organization
        """
        pass

    def test_delete_organization_role(self) -> None:
        """Test case for delete_organization_role

        Delete a role for an Organization
        """
        pass

    def test_delete_organization_settings(self) -> None:
        """Test case for delete_organization_settings

        Delete settings for an Organization
        """
        pass

    def test_delete_subscription(self) -> None:
        """Test case for delete_subscription

        Delete a subscription for an Organization
        """
        pass

    def test_delete_team(self) -> None:
        """Test case for delete_team

        Delete a team for an Organization
        """
        pass

    def test_delete_team_member(self) -> None:
        """Test case for delete_team_member

        Remove a member from a team
        """
        pass

    def test_end_trial(self) -> None:
        """Test case for end_trial

        End the trial period early for an Organization
        """
        pass

    def test_get_all_my_organizations(self) -> None:
        """Test case for get_all_my_organizations

        Get all my organizations
        """
        pass

    def test_get_all_my_organizations_with_details(self) -> None:
        """Test case for get_all_my_organizations_with_details

        Get all my organizations with details (subscriptions, ...)
        """
        pass

    def test_get_all_my_teams(self) -> None:
        """Test case for get_all_my_teams

        Get all teams for an Organization of the current user
        """
        pass

    def test_get_all_organizations(self) -> None:
        """Test case for get_all_organizations

        Get all Organizations
        """
        pass

    def test_get_checkout_session(self) -> None:
        """Test case for get_checkout_session

        Get a checkout session for an Organization
        """
        pass

    def test_get_credits_payments(self) -> None:
        """Test case for get_credits_payments

        Get all credits payments for an Organization
        """
        pass

    def test_get_customer_portal_session(self) -> None:
        """Test case for get_customer_portal_session

        Get a stripe customer portal session for an Organization
        """
        pass

    def test_get_invite(self) -> None:
        """Test case for get_invite

        Get an invite for an Organization
        """
        pass

    def test_get_invites(self) -> None:
        """Test case for get_invites

        Get all invites for an Organization
        """
        pass

    def test_get_member(self) -> None:
        """Test case for get_member

        Get a member for an Organization
        """
        pass

    def test_get_member_settings(self) -> None:
        """Test case for get_member_settings

        Get member settings for an Organization
        """
        pass

    def test_get_members(self) -> None:
        """Test case for get_members

        Get all members for an Organization
        """
        pass

    def test_get_organization(self) -> None:
        """Test case for get_organization

        Get an Organization by id
        """
        pass

    def test_get_organization_api_keys(self) -> None:
        """Test case for get_organization_api_keys

        Get all api keys for an Organization
        """
        pass

    def test_get_organization_role(self) -> None:
        """Test case for get_organization_role

        Get a role for an Organization
        """
        pass

    def test_get_organization_roles(self) -> None:
        """Test case for get_organization_roles

        Get all roles for an Organization
        """
        pass

    def test_get_organization_settings(self) -> None:
        """Test case for get_organization_settings

        Get settings for an Organization
        """
        pass

    def test_get_subscription(self) -> None:
        """Test case for get_subscription

        Get a subscription for an Organization
        """
        pass

    def test_get_team(self) -> None:
        """Test case for get_team

        Get a team for an Organization
        """
        pass

    def test_get_team_member(self) -> None:
        """Test case for get_team_member

        Get a member for a team
        """
        pass

    def test_get_team_members(self) -> None:
        """Test case for get_team_members

        Get all members for a team
        """
        pass

    def test_get_teams(self) -> None:
        """Test case for get_teams

        Get all teams for an Organization
        """
        pass

    def test_invite(self) -> None:
        """Test case for invite

        Invite a user to an Organization
        """
        pass

    def test_patch_member(self) -> None:
        """Test case for patch_member

        Patch a member for an Organization
        """
        pass

    def test_patch_member_settings(self) -> None:
        """Test case for patch_member_settings

        Patch member settings for an Organization
        """
        pass

    def test_patch_organization(self) -> None:
        """Test case for patch_organization

        Patch an Organization by ID
        """
        pass

    def test_patch_organization_api_key(self) -> None:
        """Test case for patch_organization_api_key

        Patch an api key for an Organization
        """
        pass

    def test_patch_organization_ownership(self) -> None:
        """Test case for patch_organization_ownership

        Transfer the ownership of an organization
        """
        pass

    def test_patch_organization_role(self) -> None:
        """Test case for patch_organization_role

        Patch a role for an Organization
        """
        pass

    def test_patch_organization_settings(self) -> None:
        """Test case for patch_organization_settings

        Patch settings for an Organization
        """
        pass

    def test_patch_team(self) -> None:
        """Test case for patch_team

        Patch a team for an Organization
        """
        pass

    def test_reactivate_subscription(self) -> None:
        """Test case for reactivate_subscription

        Reactivate a subscription for an Organization
        """
        pass

    def test_resend_invite(self) -> None:
        """Test case for resend_invite

        Resend Organization Invite by ID
        """
        pass

    def test_reset_organization_settings(self) -> None:
        """Test case for reset_organization_settings

        Reset settings for an Organization to default values
        """
        pass

    def test_update_subscription(self) -> None:
        """Test case for update_subscription

        Update a subscription for an Organization
        """
        pass


if __name__ == '__main__':
    unittest.main()
