# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.3.6
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.team_role_reduced_response import TeamRoleReducedResponse

class TestTeamRoleReducedResponse(unittest.TestCase):
    """TeamRoleReducedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamRoleReducedResponse:
        """Test TeamRoleReducedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamRoleReducedResponse`
        """
        model = TeamRoleReducedResponse()
        if include_optional:
            return TeamRoleReducedResponse(
                created_at = '',
                default_member_role = True,
                id = '',
                name = '',
                team_id = '',
                updated_at = ''
            )
        else:
            return TeamRoleReducedResponse(
                created_at = '',
                default_member_role = True,
                id = '',
                name = '',
                team_id = '',
                updated_at = '',
        )
        """

    def testTeamRoleReducedResponse(self):
        """Test TeamRoleReducedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
