# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.3.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.organization_member_response import OrganizationMemberResponse

class TestOrganizationMemberResponse(unittest.TestCase):
    """OrganizationMemberResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationMemberResponse:
        """Test OrganizationMemberResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationMemberResponse`
        """
        model = OrganizationMemberResponse()
        if include_optional:
            return OrganizationMemberResponse(
                created_at = '',
                created_by = '',
                created_by_name = '',
                id = '',
                invited_at = '',
                organization_id = '',
                organization_owner = True,
                organization_product_roles = [
                    core.models.role_reduced_response.RoleReducedResponse(
                        created_at = '', 
                        id = '', 
                        name = '', 
                        updated_at = '', )
                    ],
                organization_role = core.models.organization_role_reduced_response.OrganizationRoleReducedResponse(
                    created_at = '', 
                    default_member_role = True, 
                    id = '', 
                    name = '', 
                    organization_id = '', 
                    updated_at = '', ),
                updated_at = '',
                user = core.models.user_response.UserResponse(
                    created_at = '', 
                    email = '', 
                    fullname = '', 
                    id = '', 
                    updated_at = '', 
                    username = '', )
            )
        else:
            return OrganizationMemberResponse(
                created_at = '',
                created_by = '',
                created_by_name = '',
                id = '',
                invited_at = '',
                organization_id = '',
                organization_owner = True,
                organization_product_roles = [
                    core.models.role_reduced_response.RoleReducedResponse(
                        created_at = '', 
                        id = '', 
                        name = '', 
                        updated_at = '', )
                    ],
                organization_role = core.models.organization_role_reduced_response.OrganizationRoleReducedResponse(
                    created_at = '', 
                    default_member_role = True, 
                    id = '', 
                    name = '', 
                    organization_id = '', 
                    updated_at = '', ),
                updated_at = '',
                user = core.models.user_response.UserResponse(
                    created_at = '', 
                    email = '', 
                    fullname = '', 
                    id = '', 
                    updated_at = '', 
                    username = '', ),
        )
        """

    def testOrganizationMemberResponse(self):
        """Test OrganizationMemberResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
