# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.5.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.organization_credits_payment_post_request import OrganizationCreditsPaymentPostRequest

class TestOrganizationCreditsPaymentPostRequest(unittest.TestCase):
    """OrganizationCreditsPaymentPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationCreditsPaymentPostRequest:
        """Test OrganizationCreditsPaymentPostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationCreditsPaymentPostRequest`
        """
        model = OrganizationCreditsPaymentPostRequest()
        if include_optional:
            return OrganizationCreditsPaymentPostRequest(
                credits = 1
            )
        else:
            return OrganizationCreditsPaymentPostRequest(
                credits = 1,
        )
        """

    def testOrganizationCreditsPaymentPostRequest(self):
        """Test OrganizationCreditsPaymentPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
