# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.6.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.user_settings_patch_request import UserSettingsPatchRequest

class TestUserSettingsPatchRequest(unittest.TestCase):
    """UserSettingsPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserSettingsPatchRequest:
        """Test UserSettingsPatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserSettingsPatchRequest`
        """
        model = UserSettingsPatchRequest()
        if include_optional:
            return UserSettingsPatchRequest(
                color_scheme = 'auto',
                language = '',
                onboarding_done = True,
                onboarding_hold_until = '0'
            )
        else:
            return UserSettingsPatchRequest(
        )
        """

    def testUserSettingsPatchRequest(self):
        """Test UserSettingsPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
