# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.member_delete_response import MemberDeleteResponse

class TestMemberDeleteResponse(unittest.TestCase):
    """MemberDeleteResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MemberDeleteResponse:
        """Test MemberDeleteResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MemberDeleteResponse`
        """
        model = MemberDeleteResponse()
        if include_optional:
            return MemberDeleteResponse(
                id = '',
                resource_ids = [
                    ''
                    ],
                resources_action = ''
            )
        else:
            return MemberDeleteResponse(
                id = '',
                resource_ids = [
                    ''
                    ],
                resources_action = '',
        )
        """

    def testMemberDeleteResponse(self):
        """Test MemberDeleteResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
