# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.product_i18n_response import ProductI18nResponse

class TestProductI18nResponse(unittest.TestCase):
    """ProductI18nResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProductI18nResponse:
        """Test ProductI18nResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProductI18nResponse`
        """
        model = ProductI18nResponse()
        if include_optional:
            return ProductI18nResponse(
                badge = '',
                banner_text = '',
                description = '',
                features = [
                    ''
                    ],
                name = '',
                price_supplement = ''
            )
        else:
            return ProductI18nResponse(
        )
        """

    def testProductI18nResponse(self):
        """Test ProductI18nResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
