# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.organization_role_reduced_response import OrganizationRoleReducedResponse

class TestOrganizationRoleReducedResponse(unittest.TestCase):
    """OrganizationRoleReducedResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationRoleReducedResponse:
        """Test OrganizationRoleReducedResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationRoleReducedResponse`
        """
        model = OrganizationRoleReducedResponse()
        if include_optional:
            return OrganizationRoleReducedResponse(
                created_at = '',
                default_member_role = True,
                id = '',
                name = '',
                organization_id = '',
                updated_at = ''
            )
        else:
            return OrganizationRoleReducedResponse(
                created_at = '',
                default_member_role = True,
                id = '',
                name = '',
                organization_id = '',
                updated_at = '',
        )
        """

    def testOrganizationRoleReducedResponse(self):
        """Test OrganizationRoleReducedResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
