# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.4.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.user_role_response import UserRoleResponse

class TestUserRoleResponse(unittest.TestCase):
    """UserRoleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserRoleResponse:
        """Test UserRoleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserRoleResponse`
        """
        model = UserRoleResponse()
        if include_optional:
            return UserRoleResponse(
                created_at = '',
                id = '',
                role_id = '',
                updated_at = '',
                user_id = ''
            )
        else:
            return UserRoleResponse(
                created_at = '',
                id = '',
                role_id = '',
                updated_at = '',
                user_id = '',
        )
        """

    def testUserRoleResponse(self):
        """Test UserRoleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
