# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.5.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.team_response import TeamResponse

class TestTeamResponse(unittest.TestCase):
    """TeamResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TeamResponse:
        """Test TeamResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TeamResponse`
        """
        model = TeamResponse()
        if include_optional:
            return TeamResponse(
                created_at = '',
                id = '',
                members = [
                    core.models.team_member_response.TeamMemberResponse(
                        created_at = '', 
                        id = '', 
                        team_id = '', 
                        team_owner = True, 
                        team_role = core.models.team_role_reduced_response.TeamRoleReducedResponse(
                            created_at = '', 
                            default_member_role = True, 
                            id = '', 
                            name = '', 
                            team_id = '', 
                            updated_at = '', ), 
                        updated_at = '', 
                        user = core.models.user_response.UserResponse(
                            created_at = '', 
                            email = '', 
                            fullname = '', 
                            id = '', 
                            updated_at = '', 
                            username = '', ), )
                    ],
                meta_id = '',
                name = '',
                organization_id = '',
                owner = '',
                updated_at = ''
            )
        else:
            return TeamResponse(
                created_at = '',
                id = '',
                members = [
                    core.models.team_member_response.TeamMemberResponse(
                        created_at = '', 
                        id = '', 
                        team_id = '', 
                        team_owner = True, 
                        team_role = core.models.team_role_reduced_response.TeamRoleReducedResponse(
                            created_at = '', 
                            default_member_role = True, 
                            id = '', 
                            name = '', 
                            team_id = '', 
                            updated_at = '', ), 
                        updated_at = '', 
                        user = core.models.user_response.UserResponse(
                            created_at = '', 
                            email = '', 
                            fullname = '', 
                            id = '', 
                            updated_at = '', 
                            username = '', ), )
                    ],
                meta_id = '',
                name = '',
                organization_id = '',
                owner = '',
                updated_at = '',
        )
        """

    def testTeamResponse(self):
        """Test TeamResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
