# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.role_patch_request import RolePatchRequest

class TestRolePatchRequest(unittest.TestCase):
    """RolePatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RolePatchRequest:
        """Test RolePatchRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RolePatchRequest`
        """
        model = RolePatchRequest()
        if include_optional:
            return RolePatchRequest(
                default_member_role = True,
                name = '0',
                permissions = [
                    ''
                    ]
            )
        else:
            return RolePatchRequest(
        )
        """

    def testRolePatchRequest(self):
        """Test RolePatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
