# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.10.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from core.models.role_post_request import RolePostRequest

class TestRolePostRequest(unittest.TestCase):
    """RolePostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RolePostRequest:
        """Test RolePostRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RolePostRequest`
        """
        model = RolePostRequest()
        if include_optional:
            return RolePostRequest(
                default_member_role = True,
                name = '0',
                permissions = [
                    ''
                    ]
            )
        else:
            return RolePostRequest(
                name = '0',
                permissions = [
                    ''
                    ],
        )
        """

    def testRolePostRequest(self):
        """Test RolePostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
