# coding: utf-8

# flake8: noqa

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from filemanager.api.files_api import FilesApi
from filemanager.api.files_metadata_api import FilesMetadataApi
from filemanager.api.health_api import HealthApi
from filemanager.api.metrics_api import MetricsApi
from filemanager.api.version_api import VersionApi

# import ApiClient
from filemanager.api_response import ApiResponse
from filemanager.api_client import ApiClient
from filemanager.configuration import Configuration
from filemanager.exceptions import OpenApiException
from filemanager.exceptions import ApiTypeError
from filemanager.exceptions import ApiValueError
from filemanager.exceptions import ApiKeyError
from filemanager.exceptions import ApiAttributeError
from filemanager.exceptions import ApiException

# import models into sdk package
from filemanager.models.error_detail import ErrorDetail
from filemanager.models.error_response import ErrorResponse
from filemanager.models.file_metadata_batch_get_request import FileMetadataBatchGetRequest
from filemanager.models.file_metadata_batch_response import FileMetadataBatchResponse
from filemanager.models.file_metadata_response import FileMetadataResponse
from filemanager.models.file_upload_response import FileUploadResponse
from filemanager.models.file_upload_settings import FileUploadSettings
from filemanager.models.health_response import HealthResponse
from filemanager.models.version_response import VersionResponse
