# coding: utf-8

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.4.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class FileMetadataResponse(BaseModel):
    """
    FileMetadataResponse
    """ # noqa: E501
    created_at: StrictStr
    expires_at: Optional[StrictStr] = None
    file_llm_input_type: StrictStr
    file_name: StrictStr
    file_size: StrictInt
    file_storage_type: StrictStr
    id: StrictStr
    metadata: Optional[Dict[str, Any]] = None
    mime_type: StrictStr
    organization_id: Optional[StrictStr] = None
    original_file_mime_type: StrictStr
    original_file_name: StrictStr
    original_file_size: StrictInt
    original_file_storage_path: Optional[StrictStr] = None
    original_file_url: Optional[StrictStr] = None
    storage_path: StrictStr
    team_id: Optional[StrictStr] = None
    updated_at: StrictStr
    upload_category: StrictStr
    url: StrictStr
    user_id: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["created_at", "expires_at", "file_llm_input_type", "file_name", "file_size", "file_storage_type", "id", "metadata", "mime_type", "organization_id", "original_file_mime_type", "original_file_name", "original_file_size", "original_file_storage_path", "original_file_url", "storage_path", "team_id", "updated_at", "upload_category", "url", "user_id"]

    @field_validator('file_llm_input_type')
    def file_llm_input_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['embedded', 'multimodal', 'reference']):
            raise ValueError("must be one of enum values ('embedded', 'multimodal', 'reference')")
        return value

    @field_validator('file_storage_type')
    def file_storage_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['temp', 'public', 'private-org', 'private-org-user', 'private-team']):
            raise ValueError("must be one of enum values ('temp', 'public', 'private-org', 'private-org-user', 'private-team')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileMetadataResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileMetadataResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "expires_at": obj.get("expires_at"),
            "file_llm_input_type": obj.get("file_llm_input_type"),
            "file_name": obj.get("file_name"),
            "file_size": obj.get("file_size"),
            "file_storage_type": obj.get("file_storage_type"),
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "mime_type": obj.get("mime_type"),
            "organization_id": obj.get("organization_id"),
            "original_file_mime_type": obj.get("original_file_mime_type"),
            "original_file_name": obj.get("original_file_name"),
            "original_file_size": obj.get("original_file_size"),
            "original_file_storage_path": obj.get("original_file_storage_path"),
            "original_file_url": obj.get("original_file_url"),
            "storage_path": obj.get("storage_path"),
            "team_id": obj.get("team_id"),
            "updated_at": obj.get("updated_at"),
            "upload_category": obj.get("upload_category"),
            "url": obj.get("url"),
            "user_id": obj.get("user_id")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


