# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.12.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aigentchat.models.hosting_location import HostingLocation
from typing import Optional, Set
from typing_extensions import Self

class Agent(BaseModel):
    """
    Agent
    """ # noqa: E501
    assigned_tools: Optional[List[StrictStr]] = None
    attached_file_ids: Optional[List[StrictStr]] = None
    avatar_url: Optional[StrictStr] = None
    created_at: Optional[StrictInt] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    initial_user_messages: Optional[List[StrictStr]] = None
    internal_id: Optional[StrictStr] = None
    is_public: Optional[StrictBool] = None
    meta_data: Optional[Dict[str, Any]] = None
    model_host_location: Optional[HostingLocation] = None
    model_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    owner_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    owner_organization_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    parameters: Optional[Dict[str, Any]] = None
    system_messages: Optional[List[StrictStr]] = None
    updated_at: Optional[StrictInt] = None
    updated_by: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    __properties: ClassVar[List[str]] = ["assigned_tools", "attached_file_ids", "avatar_url", "created_at", "description", "id", "initial_user_messages", "internal_id", "is_public", "meta_data", "model_host_location", "model_id", "name", "owner_id", "owner_organization_id", "parameters", "system_messages", "updated_at", "updated_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Agent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Agent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assigned_tools": obj.get("assigned_tools"),
            "attached_file_ids": obj.get("attached_file_ids"),
            "avatar_url": obj.get("avatar_url"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "initial_user_messages": obj.get("initial_user_messages"),
            "internal_id": obj.get("internal_id"),
            "is_public": obj.get("is_public"),
            "meta_data": obj.get("meta_data"),
            "model_host_location": obj.get("model_host_location"),
            "model_id": obj.get("model_id"),
            "name": obj.get("name"),
            "owner_id": obj.get("owner_id"),
            "owner_organization_id": obj.get("owner_organization_id"),
            "parameters": obj.get("parameters"),
            "system_messages": obj.get("system_messages"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by")
        })
        return _obj


