# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.13.3
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from aigentchat.models.hosting_location import HostingLocation
from typing import Optional, Set
from typing_extensions import Self

class AIModelServiceObject(BaseModel):
    """
    AIModelServiceObject
    """ # noqa: E501
    cost_multiplier: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="1.0 is default, we use this to adjust our margin")
    created_at: Optional[StrictInt] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    hosting_locations: Optional[Dict[str, HostingLocation]] = None
    id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    internal_id: Optional[StrictStr] = None
    is_public: Optional[StrictBool] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    owner_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    owner_organization_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    service_impl: Annotated[str, Field(min_length=1, strict=True, max_length=64)] = Field(description="this is used for internal identification!")
    updated_at: Optional[StrictInt] = None
    updated_by: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["cost_multiplier", "created_at", "description", "hosting_locations", "id", "internal_id", "is_public", "name", "owner_id", "owner_organization_id", "service_impl", "updated_at", "updated_by"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIModelServiceObject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIModelServiceObject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "cost_multiplier": obj.get("cost_multiplier"),
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "hosting_locations": dict((_k, _v) for _k, _v in obj.get("hosting_locations").items()),
            "id": obj.get("id"),
            "internal_id": obj.get("internal_id"),
            "is_public": obj.get("is_public"),
            "name": obj.get("name"),
            "owner_id": obj.get("owner_id"),
            "owner_organization_id": obj.get("owner_organization_id"),
            "service_impl": obj.get("service_impl"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


