# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.14.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from aigentchat.models.mission_completion_reason import MissionCompletionReason
from aigentchat.models.mission_instructions import MissionInstructions
from aigentchat.models.mission_status_update_list import MissionStatusUpdateList
from typing import Optional, Set
from typing_extensions import Self

class Mission(BaseModel):
    """
    Mission
    """ # noqa: E501
    completed_at: Optional[StrictInt] = None
    completion_reason: Optional[MissionCompletionReason] = None
    content: Optional[Dict[str, Any]] = None
    created_at: Optional[StrictInt] = None
    created_by: Optional[StrictStr] = None
    creator_name: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    instructions: Optional[MissionInstructions] = None
    mission_executor_id: Optional[StrictStr] = None
    owner_id: Optional[StrictStr] = None
    owner_organization_id: Optional[StrictStr] = None
    status_updates: Optional[MissionStatusUpdateList] = None
    updated_at: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["completed_at", "completion_reason", "content", "created_at", "created_by", "creator_name", "description", "id", "instructions", "mission_executor_id", "owner_id", "owner_organization_id", "status_updates", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Mission from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of instructions
        if self.instructions:
            _dict['instructions'] = self.instructions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status_updates
        if self.status_updates:
            _dict['status_updates'] = self.status_updates.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Mission from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_at": obj.get("completed_at"),
            "completion_reason": obj.get("completion_reason"),
            "content": obj.get("content"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "creator_name": obj.get("creator_name"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "instructions": MissionInstructions.from_dict(obj["instructions"]) if obj.get("instructions") is not None else None,
            "mission_executor_id": obj.get("mission_executor_id"),
            "owner_id": obj.get("owner_id"),
            "owner_organization_id": obj.get("owner_organization_id"),
            "status_updates": MissionStatusUpdateList.from_dict(obj["status_updates"]) if obj.get("status_updates") is not None else None,
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


