# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.17.3
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from aigentchat.models.prompt_version import PromptVersion
from aigentchat.models.prompt_visibility_states import PromptVisibilityStates
from typing import Optional, Set
from typing_extensions import Self

class Prompt(BaseModel):
    """
    Prompt
    """ # noqa: E501
    created_at: Optional[StrictInt] = None
    current_version: Optional[StrictInt] = None
    default_agent_id: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    id: StrictStr
    owner_id: Optional[StrictStr] = None
    owner_organization_id: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    thumbnail_url: Optional[StrictStr] = None
    title: StrictStr
    updated_at: Optional[StrictInt] = None
    versions: Optional[List[PromptVersion]] = None
    visibility: Optional[PromptVisibilityStates] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["created_at", "current_version", "default_agent_id", "description", "id", "owner_id", "owner_organization_id", "tags", "thumbnail_url", "title", "updated_at", "versions", "visibility"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Prompt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in versions (list)
        _items = []
        if self.versions:
            for _item_versions in self.versions:
                if _item_versions:
                    _items.append(_item_versions.to_dict())
            _dict['versions'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Prompt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "current_version": obj.get("current_version"),
            "default_agent_id": obj.get("default_agent_id"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "owner_id": obj.get("owner_id"),
            "owner_organization_id": obj.get("owner_organization_id"),
            "tags": obj.get("tags"),
            "thumbnail_url": obj.get("thumbnail_url"),
            "title": obj.get("title"),
            "updated_at": obj.get("updated_at"),
            "versions": [PromptVersion.from_dict(_item) for _item in obj["versions"]] if obj.get("versions") is not None else None,
            "visibility": obj.get("visibility")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


