# coding: utf-8

"""
    Vaudience AI Core API

    API for the Vaudience AI Core

    The version of the OpenAPI document: 0.6.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from core.models.organization_role_reduced_response import OrganizationRoleReducedResponse
from core.models.role_reduced_response import RoleReducedResponse
from core.models.team_reduced_response import TeamReducedResponse
from typing import Optional, Set
from typing_extensions import Self

class OrganizationApiKeyResponse(BaseModel):
    """
    OrganizationApiKeyResponse
    """ # noqa: E501
    api_key: StrictStr = Field(alias="apiKey")
    api_key_hint: StrictStr = Field(alias="apiKeyHint")
    created_at: StrictStr = Field(alias="createdAt")
    created_by: StrictStr = Field(alias="createdBy")
    id: StrictStr
    name: StrictStr
    organization_id: StrictStr = Field(alias="organizationId")
    organization_role: OrganizationRoleReducedResponse = Field(alias="organizationRole")
    roles: List[RoleReducedResponse]
    teams: List[TeamReducedResponse]
    updated_at: StrictStr = Field(alias="updatedAt")
    user_email: StrictStr = Field(alias="userEmail")
    user_full_name: StrictStr = Field(alias="userFullName")
    user_id: StrictStr = Field(alias="userId")
    user_name: StrictStr = Field(alias="userName")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["apiKey", "apiKeyHint", "createdAt", "createdBy", "id", "name", "organizationId", "organizationRole", "roles", "teams", "updatedAt", "userEmail", "userFullName", "userId", "userName"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OrganizationApiKeyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organization_role
        if self.organization_role:
            _dict['organizationRole'] = self.organization_role.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in roles (list)
        _items = []
        if self.roles:
            for _item_roles in self.roles:
                if _item_roles:
                    _items.append(_item_roles.to_dict())
            _dict['roles'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in teams (list)
        _items = []
        if self.teams:
            for _item_teams in self.teams:
                if _item_teams:
                    _items.append(_item_teams.to_dict())
            _dict['teams'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OrganizationApiKeyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiKey": obj.get("apiKey"),
            "apiKeyHint": obj.get("apiKeyHint"),
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "organizationId": obj.get("organizationId"),
            "organizationRole": OrganizationRoleReducedResponse.from_dict(obj["organizationRole"]) if obj.get("organizationRole") is not None else None,
            "roles": [RoleReducedResponse.from_dict(_item) for _item in obj["roles"]] if obj.get("roles") is not None else None,
            "teams": [TeamReducedResponse.from_dict(_item) for _item in obj["teams"]] if obj.get("teams") is not None else None,
            "updatedAt": obj.get("updatedAt"),
            "userEmail": obj.get("userEmail"),
            "userFullName": obj.get("userFullName"),
            "userId": obj.get("userId"),
            "userName": obj.get("userName")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


