# coding: utf-8

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.22.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from filemanager.models.collection_summary import CollectionSummary

class TestCollectionSummary(unittest.TestCase):
    """CollectionSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CollectionSummary:
        """Test CollectionSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CollectionSummary`
        """
        model = CollectionSummary()
        if include_optional:
            return CollectionSummary(
                total_collections = 56,
                total_collections_per_user = 56,
                total_files = 56,
                total_size = 56,
                total_tokens = 56
            )
        else:
            return CollectionSummary(
        )
        """

    def testCollectionSummary(self):
        """Test CollectionSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
