# coding: utf-8

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from filemanager.api.files_metadata_api import FilesMetadataApi


class TestFilesMetadataApi(unittest.TestCase):
    """FilesMetadataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesMetadataApi()

    def tearDown(self) -> None:
        pass

    def test_get_file_metadata(self) -> None:
        """Test case for get_file_metadata

        Get file metadata by path
        """
        pass

    def test_get_file_metadata_batch(self) -> None:
        """Test case for get_file_metadata_batch

        Get metadata for multiple files
        """
        pass


if __name__ == '__main__':
    unittest.main()
