# coding: utf-8

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from filemanager.api.files_api import FilesApi


class TestFilesApi(unittest.TestCase):
    """FilesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FilesApi()

    def tearDown(self) -> None:
        pass

    def test_delete_file(self) -> None:
        """Test case for delete_file

        Delete a file
        """
        pass

    def test_get_file_upload_categories(self) -> None:
        """Test case for get_file_upload_categories

        Get file upload categories
        """
        pass

    def test_serve_file(self) -> None:
        """Test case for serve_file

        Serve a file
        """
        pass

    def test_upload_file(self) -> None:
        """Test case for upload_file

        Create a file for a channel
        """
        pass


if __name__ == '__main__':
    unittest.main()
