# coding: utf-8

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.4.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from filemanager.models.file_duplicate_request import FileDuplicateRequest

class TestFileDuplicateRequest(unittest.TestCase):
    """FileDuplicateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileDuplicateRequest:
        """Test FileDuplicateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileDuplicateRequest`
        """
        model = FileDuplicateRequest()
        if include_optional:
            return FileDuplicateRequest(
                storage_path = ''
            )
        else:
            return FileDuplicateRequest(
                storage_path = '',
        )
        """

    def testFileDuplicateRequest(self):
        """Test FileDuplicateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
