# coding: utf-8

"""
    vAudience AI File Manager API

    API for the vAudience AI File Manager

    The version of the OpenAPI document: 0.2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from filemanager.models.file_metadata_batch_response import FileMetadataBatchResponse

class TestFileMetadataBatchResponse(unittest.TestCase):
    """FileMetadataBatchResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileMetadataBatchResponse:
        """Test FileMetadataBatchResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileMetadataBatchResponse`
        """
        model = FileMetadataBatchResponse()
        if include_optional:
            return FileMetadataBatchResponse(
                files = [
                    filemanager.models.file_metadata_response.FileMetadataResponse(
                        created_at = '', 
                        expires_at = '', 
                        file_name = '', 
                        file_size = 56, 
                        id = '', 
                        metadata = filemanager.models.metadata.metadata(), 
                        mime_type = '', 
                        organization_id = '', 
                        original_file_name = '', 
                        original_file_size = 56, 
                        original_mime_type = '', 
                        original_url = '', 
                        storage_path = '', 
                        storage_type = 'temp', 
                        team_id = '', 
                        updated_at = '', 
                        upload_category = '', 
                        url = '', 
                        user_id = '', )
                    ]
            )
        else:
            return FileMetadataBatchResponse(
                files = [
                    filemanager.models.file_metadata_response.FileMetadataResponse(
                        created_at = '', 
                        expires_at = '', 
                        file_name = '', 
                        file_size = 56, 
                        id = '', 
                        metadata = filemanager.models.metadata.metadata(), 
                        mime_type = '', 
                        organization_id = '', 
                        original_file_name = '', 
                        original_file_size = 56, 
                        original_mime_type = '', 
                        original_url = '', 
                        storage_path = '', 
                        storage_type = 'temp', 
                        team_id = '', 
                        updated_at = '', 
                        upload_category = '', 
                        url = '', 
                        user_id = '', )
                    ],
        )
        """

    def testFileMetadataBatchResponse(self):
        """Test FileMetadataBatchResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
