# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.29.5
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.tag_write_dto import TagWriteDto

class TestTagWriteDto(unittest.TestCase):
    """TagWriteDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagWriteDto:
        """Test TagWriteDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagWriteDto`
        """
        model = TagWriteDto()
        if include_optional:
            return TagWriteDto(
                internal_id = '',
                is_public = True,
                name = '0',
                type = ''
            )
        else:
            return TagWriteDto(
        )
        """

    def testTagWriteDto(self):
        """Test TagWriteDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
