# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.30.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.a_igency_message_file import AIgencyMessageFile

class TestAIgencyMessageFile(unittest.TestCase):
    """AIgencyMessageFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIgencyMessageFile:
        """Test AIgencyMessageFile
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIgencyMessageFile`
        """
        model = AIgencyMessageFile()
        if include_optional:
            return AIgencyMessageFile(
                embedded_content = '',
                file_name = '',
                file_size = 56,
                id = '',
                llm_input_type = '',
                meta_data = aigentchat.models.meta_data.meta_data(),
                mime_type = '',
                upload_category = '',
                url = ''
            )
        else:
            return AIgencyMessageFile(
                embedded_content = '',
                file_name = '',
                file_size = 56,
                id = '',
                llm_input_type = '',
                meta_data = aigentchat.models.meta_data.meta_data(),
                mime_type = '',
                upload_category = '',
                url = '',
        )
        """

    def testAIgencyMessageFile(self):
        """Test AIgencyMessageFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
