# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.21.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.ai_model_service_with_models import AIModelServiceWithModels

class TestAIModelServiceWithModels(unittest.TestCase):
    """AIModelServiceWithModels unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIModelServiceWithModels:
        """Test AIModelServiceWithModels
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIModelServiceWithModels`
        """
        model = AIModelServiceWithModels()
        if include_optional:
            return AIModelServiceWithModels(
                models = [
                    aigentchat.models.ai_model.AIModel(
                        abilities = [
                            aigentchat.models.ability.Ability(
                                constraints = [
                                    aigentchat.models.ai_model_constraint.AIModelConstraint(
                                        direction = 'input', 
                                        max = 56, 
                                        min = 56, 
                                        unit = 'tokens', )
                                    ], 
                                type = 'text', )
                            ], 
                        abilities_v2 = [
                            aigentchat.models.ability_v2.AbilityV2()
                            ], 
                        accepted_file_mimetypes = [
                            ''
                            ], 
                        created_at = 56, 
                        description = '', 
                        documentation_url = '', 
                        features = [
                            aigentchat.models.ai_model_feature.AIModelFeature(
                                capability = '', 
                                cost_item_templates = [
                                    aigentchat.models.execution_cost_template.ExecutionCostTemplate(
                                        batch_cost_factor = 1.337, 
                                        cost_per_unit_in_euro = 1.337, 
                                        cost_unit = 'input-tokens-per-million', 
                                        description = '', )
                                    ], 
                                cost_items = [
                                    aigentchat.models.execution_usage_cost.ExecutionUsageCost(
                                        batch_cost_factor = 1.337, 
                                        cost_per_unit_in_euro = 1.337, 
                                        description = '', 
                                        resulting_cost_in_euro = 1.337, 
                                        used_units = 1.337, )
                                    ], )
                            ], 
                        i18n = {
                            'key' : aigentchat.models.ai_model_i18n.AIModelI18n(
                                description = '', 
                                model_category = '', 
                                name = '0', )
                            }, 
                        id = '0', 
                        internal_id = '', 
                        is_public = True, 
                        lifecycle = '', 
                        model_category = '', 
                        model_id = '0', 
                        model_release_date = 56, 
                        name = '0', 
                        owner_id = '0', 
                        owner_organization_id = '0', 
                        parameter_definitions = aigentchat.models.parameter_definitions.parameter_definitions(), 
                        parameters = aigentchat.models.parameters.parameters(), 
                        service_host_locations = [
                            ''
                            ], 
                        service_id = '0', 
                        updated_at = 56, 
                        updated_by = '', )
                    ],
                service = aigentchat.models.ai_model_service_object.AIModelServiceObject(
                    cost_multiplier = 1.337, 
                    created_at = 56, 
                    description = '', 
                    hosting_locations = {
                        'key' : ''
                        }, 
                    i18n = {
                        'key' : aigentchat.models.ai_model_service_i18n.AIModelServiceI18n(
                            description = '', 
                            name = '0', )
                        }, 
                    id = '0', 
                    internal_id = '', 
                    is_public = True, 
                    name = '0', 
                    owner_id = '0', 
                    owner_organization_id = '0', 
                    service_impl = aigentchat.models.service_impl.service_impl(), 
                    updated_at = 56, 
                    updated_by = '', )
            )
        else:
            return AIModelServiceWithModels(
        )
        """

    def testAIModelServiceWithModels(self):
        """Test AIModelServiceWithModels"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
