# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.28.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.tool_function import ToolFunction

class TestToolFunction(unittest.TestCase):
    """ToolFunction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToolFunction:
        """Test ToolFunction
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToolFunction`
        """
        model = ToolFunction()
        if include_optional:
            return ToolFunction(
                description = '',
                hosting_location = '',
                i18n = {
                    'key' : aigentchat.models.tool_i18n.ToolI18n(
                        description = '', 
                        name = '', )
                    },
                icon = '',
                id = '',
                name = '',
                parameters = '',
                response_visible = True,
                tool_id = '',
                version = ''
            )
        else:
            return ToolFunction(
                id = '',
                name = '',
                response_visible = True,
                tool_id = '',
                version = '',
        )
        """

    def testToolFunction(self):
        """Test ToolFunction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
