# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.23.2
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.a_igency_message_file_list import AIgencyMessageFileList

class TestAIgencyMessageFileList(unittest.TestCase):
    """AIgencyMessageFileList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIgencyMessageFileList:
        """Test AIgencyMessageFileList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIgencyMessageFileList`
        """
        model = AIgencyMessageFileList()
        if include_optional:
            return AIgencyMessageFileList(
                files = [
                    aigentchat.models.a_igency_message_file.AIgencyMessageFile(
                        embedded_content = '', 
                        file_name = '', 
                        file_size = 56, 
                        id = '', 
                        llm_input_type = '', 
                        meta_data = aigentchat.models.meta_data.meta_data(), 
                        mime_type = '', 
                        upload_category = '', 
                        url = '', )
                    ]
            )
        else:
            return AIgencyMessageFileList(
                files = [
                    aigentchat.models.a_igency_message_file.AIgencyMessageFile(
                        embedded_content = '', 
                        file_name = '', 
                        file_size = 56, 
                        id = '', 
                        llm_input_type = '', 
                        meta_data = aigentchat.models.meta_data.meta_data(), 
                        mime_type = '', 
                        upload_category = '', 
                        url = '', )
                    ],
        )
        """

    def testAIgencyMessageFileList(self):
        """Test AIgencyMessageFileList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
