# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.29.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.finish_reason import FinishReason

class TestFinishReason(unittest.TestCase):
    """FinishReason unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFinishReason(self):
        """Test FinishReason"""
        # inst = FinishReason()

if __name__ == '__main__':
    unittest.main()
