# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.30.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.prompt_version import PromptVersion

class TestPromptVersion(unittest.TestCase):
    """PromptVersion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptVersion:
        """Test PromptVersion
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptVersion`
        """
        model = PromptVersion()
        if include_optional:
            return PromptVersion(
                content = '',
                created_at = 56,
                created_by = '',
                structured_content = [
                    aigentchat.models.prompt_content.PromptContent(
                        constant = aigentchat.models.prompt_constant.PromptConstant(
                            name = '', ), 
                        prompt = aigentchat.models.prompt_reference.PromptReference(
                            id = '', 
                            vars = {
                                'key' : ''
                                }, 
                            version = 56, ), 
                        text = '', 
                        type = aigentchat.models.type.type(), 
                        variable = aigentchat.models.prompt_variable.PromptVariable(
                            default = '', 
                            description = '', 
                            multi = True, 
                            name = '', 
                            options = [
                                aigentchat.models.prompt_variable_option.PromptVariableOption(
                                    label = '', 
                                    value = '', )
                                ], ), )
                    ],
                version = 56
            )
        else:
            return PromptVersion(
        )
        """

    def testPromptVersion(self):
        """Test PromptVersion"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
