# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.22.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.prompt_write_dto import PromptWriteDto

class TestPromptWriteDto(unittest.TestCase):
    """PromptWriteDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptWriteDto:
        """Test PromptWriteDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptWriteDto`
        """
        model = PromptWriteDto()
        if include_optional:
            return PromptWriteDto(
                content = '',
                default_agent_id = '',
                description = '',
                tags = [
                    ''
                    ],
                thumbnail_url = '',
                title = '',
                visibility = 'private'
            )
        else:
            return PromptWriteDto(
        )
        """

    def testPromptWriteDto(self):
        """Test PromptWriteDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
