# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.28.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.function_call_i18n import FunctionCallI18n

class TestFunctionCallI18n(unittest.TestCase):
    """FunctionCallI18n unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FunctionCallI18n:
        """Test FunctionCallI18n
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FunctionCallI18n`
        """
        model = FunctionCallI18n()
        if include_optional:
            return FunctionCallI18n(
                description = '',
                name = ''
            )
        else:
            return FunctionCallI18n(
        )
        """

    def testFunctionCallI18n(self):
        """Test FunctionCallI18n"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
