# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.29.5
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.a_igency_function_status_update import AIgencyFunctionStatusUpdate

class TestAIgencyFunctionStatusUpdate(unittest.TestCase):
    """AIgencyFunctionStatusUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIgencyFunctionStatusUpdate:
        """Test AIgencyFunctionStatusUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIgencyFunctionStatusUpdate`
        """
        model = AIgencyFunctionStatusUpdate()
        if include_optional:
            return AIgencyFunctionStatusUpdate(
                id = '0',
                updates = [
                    aigentchat.models.a_igency_function_status_update_data.AIgencyFunctionStatusUpdateData(
                        message = '', 
                        meta_data = aigentchat.models.meta_data.meta_data(), )
                    ]
            )
        else:
            return AIgencyFunctionStatusUpdate(
                id = '0',
                updates = [
                    aigentchat.models.a_igency_function_status_update_data.AIgencyFunctionStatusUpdateData(
                        message = '', 
                        meta_data = aigentchat.models.meta_data.meta_data(), )
                    ],
        )
        """

    def testAIgencyFunctionStatusUpdate(self):
        """Test AIgencyFunctionStatusUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
