# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.30.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.prompt_variable import PromptVariable

class TestPromptVariable(unittest.TestCase):
    """PromptVariable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PromptVariable:
        """Test PromptVariable
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PromptVariable`
        """
        model = PromptVariable()
        if include_optional:
            return PromptVariable(
                default = '',
                description = '',
                multi = True,
                name = '',
                options = [
                    aigentchat.models.prompt_variable_option.PromptVariableOption(
                        label = '', 
                        value = '', )
                    ]
            )
        else:
            return PromptVariable(
                name = '',
        )
        """

    def testPromptVariable(self):
        """Test PromptVariable"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
