# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.28.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.a_igency_message_content_list import AIgencyMessageContentList

class TestAIgencyMessageContentList(unittest.TestCase):
    """AIgencyMessageContentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIgencyMessageContentList:
        """Test AIgencyMessageContentList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIgencyMessageContentList`
        """
        model = AIgencyMessageContentList()
        if include_optional:
            return AIgencyMessageContentList(
                data = [
                    aigentchat.models.a_igency_message_content.AIgencyMessageContent(
                        file = aigentchat.models.a_igency_message_file.AIgencyMessageFile(
                            embedded_content = '', 
                            file_name = '', 
                            file_size = 56, 
                            id = '', 
                            llm_input_type = '', 
                            meta_data = aigentchat.models.meta_data.meta_data(), 
                            mime_type = '', 
                            upload_category = '', 
                            url = '', ), 
                        function_call = aigentchat.models.a_igency_function_call.AIgencyFunctionCall(
                            arguments = aigentchat.models.arguments.arguments(), 
                            function_name = '0', 
                            id = '0', 
                            tool_function_id = '', ), 
                        function_responses = aigentchat.models.a_igency_function_response.AIgencyFunctionResponse(
                            continuation_instructions = aigentchat.models.tool_continuation_instructions.ToolContinuationInstructions(
                                continuation_function_call = '', 
                                continuation_id = '', 
                                human_input_prompt = '', ), 
                            function_name = '0', 
                            id = '0', 
                            is_error = True, 
                            result = '', 
                            result_files = [
                                aigentchat.models.a_igency_message_file.AIgencyMessageFile(
                                    embedded_content = '', 
                                    file_name = '', 
                                    file_size = 56, 
                                    id = '', 
                                    llm_input_type = '', 
                                    meta_data = aigentchat.models.meta_data.meta_data(), 
                                    mime_type = '', 
                                    upload_category = '', 
                                    url = '', )
                                ], 
                            result_meta_data = aigentchat.models.result_meta_data.result_meta_data(), 
                            tool_function_id = '', ), 
                        function_status_update = aigentchat.models.a_igency_function_status_update.AIgencyFunctionStatusUpdate(
                            id = '0', 
                            updates = [
                                aigentchat.models.a_igency_function_status_update_data.AIgencyFunctionStatusUpdateData(
                                    message = '', 
                                    meta_data = aigentchat.models.meta_data.meta_data(), )
                                ], ), 
                        text = '', 
                        text_meta_data = {
                            'key' : None
                            }, 
                        text_mime_type = '', 
                        thinking = aigentchat.models.a_igency_thinking.AIgencyThinking(
                            content = '', 
                            is_redacted = True, 
                            signature = '', ), 
                        type = 'text', )
                    ],
                full_text = '',
                full_text_mime_type = ''
            )
        else:
            return AIgencyMessageContentList(
                data = [
                    aigentchat.models.a_igency_message_content.AIgencyMessageContent(
                        file = aigentchat.models.a_igency_message_file.AIgencyMessageFile(
                            embedded_content = '', 
                            file_name = '', 
                            file_size = 56, 
                            id = '', 
                            llm_input_type = '', 
                            meta_data = aigentchat.models.meta_data.meta_data(), 
                            mime_type = '', 
                            upload_category = '', 
                            url = '', ), 
                        function_call = aigentchat.models.a_igency_function_call.AIgencyFunctionCall(
                            arguments = aigentchat.models.arguments.arguments(), 
                            function_name = '0', 
                            id = '0', 
                            tool_function_id = '', ), 
                        function_responses = aigentchat.models.a_igency_function_response.AIgencyFunctionResponse(
                            continuation_instructions = aigentchat.models.tool_continuation_instructions.ToolContinuationInstructions(
                                continuation_function_call = '', 
                                continuation_id = '', 
                                human_input_prompt = '', ), 
                            function_name = '0', 
                            id = '0', 
                            is_error = True, 
                            result = '', 
                            result_files = [
                                aigentchat.models.a_igency_message_file.AIgencyMessageFile(
                                    embedded_content = '', 
                                    file_name = '', 
                                    file_size = 56, 
                                    id = '', 
                                    llm_input_type = '', 
                                    meta_data = aigentchat.models.meta_data.meta_data(), 
                                    mime_type = '', 
                                    upload_category = '', 
                                    url = '', )
                                ], 
                            result_meta_data = aigentchat.models.result_meta_data.result_meta_data(), 
                            tool_function_id = '', ), 
                        function_status_update = aigentchat.models.a_igency_function_status_update.AIgencyFunctionStatusUpdate(
                            id = '0', 
                            updates = [
                                aigentchat.models.a_igency_function_status_update_data.AIgencyFunctionStatusUpdateData(
                                    message = '', 
                                    meta_data = aigentchat.models.meta_data.meta_data(), )
                                ], ), 
                        text = '', 
                        text_meta_data = {
                            'key' : None
                            }, 
                        text_mime_type = '', 
                        thinking = aigentchat.models.a_igency_thinking.AIgencyThinking(
                            content = '', 
                            is_redacted = True, 
                            signature = '', ), 
                        type = 'text', )
                    ],
                full_text = '',
        )
        """

    def testAIgencyMessageContentList(self):
        """Test AIgencyMessageContentList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
