# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.27.3
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.api.org_cost_budgets_api import OrgCostBudgetsApi


class TestOrgCostBudgetsApi(unittest.TestCase):
    """OrgCostBudgetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrgCostBudgetsApi()

    def tearDown(self) -> None:
        pass

    def test_add_new_org_cost_budget(self) -> None:
        """Test case for add_new_org_cost_budget

        Add new organization cost budget
        """
        pass

    def test_check_org_cost_budget(self) -> None:
        """Test case for check_org_cost_budget

        Check organization cost budget
        """
        pass

    def test_get_org_cost_budget(self) -> None:
        """Test case for get_org_cost_budget

        Get organization cost budget
        """
        pass

    def test_update_org_cost_budget(self) -> None:
        """Test case for update_org_cost_budget

        Update organization cost budget
        """
        pass


if __name__ == '__main__':
    unittest.main()
