# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.25.2
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.tag import Tag

class TestTag(unittest.TestCase):
    """Tag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Tag:
        """Test Tag
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Tag`
        """
        model = Tag()
        if include_optional:
            return Tag(
                created_at = 56,
                i18n = {
                    'key' : aigentchat.models.tag_i18n.TagI18n(
                        name = '0', )
                    },
                id = '0',
                internal_id = '',
                is_public = True,
                name = '0',
                organization_id = '0',
                type = 'agent',
                updated_at = 56,
                updated_by = '0'
            )
        else:
            return Tag(
                id = '0',
                name = '0',
                organization_id = '0',
                type = 'agent',
        )
        """

    def testTag(self):
        """Test Tag"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
