# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.30.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.agent_write_dto import AgentWriteDto

class TestAgentWriteDto(unittest.TestCase):
    """AgentWriteDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgentWriteDto:
        """Test AgentWriteDto
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgentWriteDto`
        """
        model = AgentWriteDto()
        if include_optional:
            return AgentWriteDto(
                add_tool_guidelines = True,
                assigned_tools = [
                    ''
                    ],
                attached_file_ids = [
                    ''
                    ],
                avatar_url = '',
                default_file_upload_category = '',
                description = '',
                i18n = {
                    'key' : aigentchat.models.agent_i18n.AgentI18n(
                        description = '', 
                        name = '0', )
                    },
                ignore_incoming_overwrite = True,
                initial_user_messages = [
                    ''
                    ],
                initial_user_prompt = [
                    aigentchat.models.prompt_content.PromptContent(
                        constant = aigentchat.models.prompt_constant.PromptConstant(
                            name = '', ), 
                        prompt = aigentchat.models.prompt_reference.PromptReference(
                            id = '', 
                            vars = {
                                'key' : ''
                                }, 
                            version = 56, ), 
                        text = '', 
                        type = aigentchat.models.type.type(), 
                        variable = aigentchat.models.prompt_variable.PromptVariable(
                            default = '', 
                            description = '', 
                            multi = True, 
                            name = '', 
                            options = [
                                aigentchat.models.prompt_variable_option.PromptVariableOption(
                                    label = '', 
                                    value = '', )
                                ], ), )
                    ],
                internal_id = '',
                meta_data = None,
                model_actions = [
                    ''
                    ],
                model_host_location = '',
                model_id = '0',
                name = '0',
                parameters = None,
                read_access = aigentchat.models.access_scope.AccessScope(
                    has_teams = True, 
                    include_organization = True, 
                    is_private = True, 
                    is_public = True, 
                    team_ids = [
                        ''
                        ], 
                    user_ids = [
                        ''
                        ], ),
                system_messages = [
                    ''
                    ],
                system_prompt = [
                    aigentchat.models.prompt_content.PromptContent(
                        constant = aigentchat.models.prompt_constant.PromptConstant(
                            name = '', ), 
                        prompt = aigentchat.models.prompt_reference.PromptReference(
                            id = '', 
                            vars = {
                                'key' : ''
                                }, 
                            version = 56, ), 
                        text = '', 
                        type = aigentchat.models.type.type(), 
                        variable = aigentchat.models.prompt_variable.PromptVariable(
                            default = '', 
                            description = '', 
                            multi = True, 
                            name = '', 
                            options = [
                                aigentchat.models.prompt_variable_option.PromptVariableOption(
                                    label = '', 
                                    value = '', )
                                ], ), )
                    ],
                system_tags = [
                    ''
                    ],
                tags = [
                    ''
                    ],
                tool_config = None,
                type = '',
                use_tools = True,
                write_access = aigentchat.models.access_scope.AccessScope(
                    has_teams = True, 
                    include_organization = True, 
                    is_private = True, 
                    is_public = True, 
                    team_ids = [
                        ''
                        ], 
                    user_ids = [
                        ''
                        ], )
            )
        else:
            return AgentWriteDto(
        )
        """

    def testAgentWriteDto(self):
        """Test AgentWriteDto"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
