# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.50.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.a_igency_message_completion_parameters import AIgencyMessageCompletionParameters

class TestAIgencyMessageCompletionParameters(unittest.TestCase):
    """AIgencyMessageCompletionParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AIgencyMessageCompletionParameters:
        """Test AIgencyMessageCompletionParameters
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AIgencyMessageCompletionParameters`
        """
        model = AIgencyMessageCompletionParameters()
        if include_optional:
            return AIgencyMessageCompletionParameters(
                agent_id = '',
                assigned_collection_ids = [
                    ''
                    ],
                continue_instruction_on_max_tokens = '',
                continue_on_max_tokens = True,
                deepr_tool_auto_activated = True,
                model_host_location = '',
                model_parameters = aigentchat.models.model_parameters.model_parameters(),
                selected_tools = [
                    ''
                    ],
                set_message_history_ids = [
                    ''
                    ],
                stream = True,
                tool_configs = aigentchat.models.tool_configs.tool_configs(),
                tool_function_ids = [
                    ''
                    ],
                use_channel_messages_as_history = True,
                use_tools = True,
                var_replacements = {
                    'key' : ''
                    }
            )
        else:
            return AIgencyMessageCompletionParameters(
        )
        """

    def testAIgencyMessageCompletionParameters(self):
        """Test AIgencyMessageCompletionParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
