# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.22.9
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aigentchat.models.chat_completion_cost_tracking_request import ChatCompletionCostTrackingRequest

class TestChatCompletionCostTrackingRequest(unittest.TestCase):
    """ChatCompletionCostTrackingRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatCompletionCostTrackingRequest:
        """Test ChatCompletionCostTrackingRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatCompletionCostTrackingRequest`
        """
        model = ChatCompletionCostTrackingRequest()
        if include_optional:
            return ChatCompletionCostTrackingRequest(
                batch = True,
                execution_id = '',
                input_tokens = 0,
                model_internal_id = '',
                output_tokens = 0,
                service_internal_id = '',
                streaming = True,
                user_id = ''
            )
        else:
            return ChatCompletionCostTrackingRequest(
                model_internal_id = '',
                service_internal_id = '',
        )
        """

    def testChatCompletionCostTrackingRequest(self):
        """Test ChatCompletionCostTrackingRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
