# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.25.3
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from aigentchat.models.a_igency_function_call import AIgencyFunctionCall
from aigentchat.models.a_igency_function_response import AIgencyFunctionResponse
from aigentchat.models.a_igency_function_status_update import AIgencyFunctionStatusUpdate
from aigentchat.models.a_igency_message_content_type import AIgencyMessageContentType
from aigentchat.models.a_igency_message_file import AIgencyMessageFile
from aigentchat.models.a_igency_thinking import AIgencyThinking
from typing import Optional, Set
from typing_extensions import Self

class AIgencyMessageContent(BaseModel):
    """
    AIgencyMessageContent
    """ # noqa: E501
    file: Optional[AIgencyMessageFile] = None
    function_call: Optional[AIgencyFunctionCall] = None
    function_responses: Optional[AIgencyFunctionResponse] = None
    function_status_update: Optional[AIgencyFunctionStatusUpdate] = None
    text: Optional[StrictStr] = None
    thinking: Optional[AIgencyThinking] = None
    type: AIgencyMessageContentType
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["file", "function_call", "function_responses", "function_status_update", "text", "thinking", "type"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIgencyMessageContent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of file
        if self.file:
            _dict['file'] = self.file.to_dict()
        # override the default output from pydantic by calling `to_dict()` of function_call
        if self.function_call:
            _dict['function_call'] = self.function_call.to_dict()
        # override the default output from pydantic by calling `to_dict()` of function_responses
        if self.function_responses:
            _dict['function_responses'] = self.function_responses.to_dict()
        # override the default output from pydantic by calling `to_dict()` of function_status_update
        if self.function_status_update:
            _dict['function_status_update'] = self.function_status_update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of thinking
        if self.thinking:
            _dict['thinking'] = self.thinking.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIgencyMessageContent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "file": AIgencyMessageFile.from_dict(obj["file"]) if obj.get("file") is not None else None,
            "function_call": AIgencyFunctionCall.from_dict(obj["function_call"]) if obj.get("function_call") is not None else None,
            "function_responses": AIgencyFunctionResponse.from_dict(obj["function_responses"]) if obj.get("function_responses") is not None else None,
            "function_status_update": AIgencyFunctionStatusUpdate.from_dict(obj["function_status_update"]) if obj.get("function_status_update") is not None else None,
            "text": obj.get("text"),
            "thinking": AIgencyThinking.from_dict(obj["thinking"]) if obj.get("thinking") is not None else None,
            "type": obj.get("type")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


