# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.29.5
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aigentchat.models.a_igency_message_content_list import AIgencyMessageContentList
from aigentchat.models.a_igency_message_file_list import AIgencyMessageFileList
from aigentchat.models.a_igency_message_type import AIgencyMessageType
from aigentchat.models.ai_service_error import AiServiceError
from aigentchat.models.conversation_role import ConversationRole
from aigentchat.models.execution_feature_usage import ExecutionFeatureUsage
from aigentchat.models.finish_reason import FinishReason
from aigentchat.models.token_direction import TokenDirection
from aigentchat.models.tool_continuation_instructions import ToolContinuationInstructions
from typing import Optional, Set
from typing_extensions import Self

class AIgencyMessage(BaseModel):
    """
    AIgencyMessage
    """ # noqa: E501
    ai_model_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    ai_service_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    attachments: AIgencyMessageFileList = Field(description="Note: deprecated, but we need to keep it for backward compatibility or do a message data migration")
    channel_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    channel_name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    content: AIgencyMessageContentList
    continuation_instructions: Optional[ToolContinuationInstructions] = None
    created_at: StrictInt
    error: Optional[AiServiceError] = None
    execution_id: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    feature_usage: Optional[List[ExecutionFeatureUsage]] = None
    finish_reason: Optional[FinishReason] = None
    id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    meta_data: Optional[Dict[str, Any]] = None
    owner_organization_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    parameters: Optional[Dict[str, Any]] = None
    reference_id: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    response_to_id: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    sender_conversation_role: ConversationRole
    sender_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    sender_name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    state: Optional[StrictStr] = None
    token_count: Optional[StrictInt] = None
    token_direction: TokenDirection
    type: AIgencyMessageType
    updated_at: StrictInt
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["ai_model_id", "ai_service_id", "attachments", "channel_id", "channel_name", "content", "continuation_instructions", "created_at", "error", "execution_id", "feature_usage", "finish_reason", "id", "meta_data", "owner_organization_id", "parameters", "reference_id", "response_to_id", "sender_conversation_role", "sender_id", "sender_name", "state", "token_count", "token_direction", "type", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIgencyMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attachments
        if self.attachments:
            _dict['attachments'] = self.attachments.to_dict()
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of continuation_instructions
        if self.continuation_instructions:
            _dict['continuation_instructions'] = self.continuation_instructions.to_dict()
        # override the default output from pydantic by calling `to_dict()` of error
        if self.error:
            _dict['error'] = self.error.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in feature_usage (list)
        _items = []
        if self.feature_usage:
            for _item_feature_usage in self.feature_usage:
                if _item_feature_usage:
                    _items.append(_item_feature_usage.to_dict())
            _dict['feature_usage'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIgencyMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ai_model_id": obj.get("ai_model_id"),
            "ai_service_id": obj.get("ai_service_id"),
            "attachments": AIgencyMessageFileList.from_dict(obj["attachments"]) if obj.get("attachments") is not None else None,
            "channel_id": obj.get("channel_id"),
            "channel_name": obj.get("channel_name"),
            "content": AIgencyMessageContentList.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "continuation_instructions": ToolContinuationInstructions.from_dict(obj["continuation_instructions"]) if obj.get("continuation_instructions") is not None else None,
            "created_at": obj.get("created_at"),
            "error": AiServiceError.from_dict(obj["error"]) if obj.get("error") is not None else None,
            "execution_id": obj.get("execution_id"),
            "feature_usage": [ExecutionFeatureUsage.from_dict(_item) for _item in obj["feature_usage"]] if obj.get("feature_usage") is not None else None,
            "finish_reason": obj.get("finish_reason"),
            "id": obj.get("id"),
            "meta_data": obj.get("meta_data"),
            "owner_organization_id": obj.get("owner_organization_id"),
            "parameters": obj.get("parameters"),
            "reference_id": obj.get("reference_id"),
            "response_to_id": obj.get("response_to_id"),
            "sender_conversation_role": obj.get("sender_conversation_role"),
            "sender_id": obj.get("sender_id"),
            "sender_name": obj.get("sender_name"),
            "state": obj.get("state"),
            "token_count": obj.get("token_count"),
            "token_direction": obj.get("token_direction"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


