# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.23.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AgentType(str, Enum):
    """
    AgentType
    """

    """
    allowed enum values
    """
    AgentTypeNil = ''
    AgentTypeBasic = 'basic'
    AgentTypeService = 'service'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AgentType from a JSON string"""
        return cls(json.loads(json_str))


