# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.29.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from aigentchat.models.ai_model_service_i18n import AIModelServiceI18n
from aigentchat.models.hosting_location import HostingLocation
from typing import Optional, Set
from typing_extensions import Self

class AIModelServiceWriteDto(BaseModel):
    """
    AIModelServiceWriteDto
    """ # noqa: E501
    ai_service_id: Optional[StrictStr] = None
    cost_multiplier: Optional[Union[StrictFloat, StrictInt]] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    hosting_locations: Optional[Dict[str, HostingLocation]] = None
    i18n: Optional[Dict[str, AIModelServiceI18n]] = None
    internal_id: Optional[StrictStr] = None
    is_public: Optional[StrictBool] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["ai_service_id", "cost_multiplier", "description", "hosting_locations", "i18n", "internal_id", "is_public", "name"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIModelServiceWriteDto from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in i18n (dict)
        _field_dict = {}
        if self.i18n:
            for _key_i18n in self.i18n:
                if self.i18n[_key_i18n]:
                    _field_dict[_key_i18n] = self.i18n[_key_i18n].to_dict()
            _dict['i18n'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIModelServiceWriteDto from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ai_service_id": obj.get("ai_service_id"),
            "cost_multiplier": obj.get("cost_multiplier"),
            "description": obj.get("description"),
            "hosting_locations": dict((_k, _v) for _k, _v in obj.get("hosting_locations").items()) if obj.get("hosting_locations") is not None else None,
            "i18n": dict(
                (_k, AIModelServiceI18n.from_dict(_v))
                for _k, _v in obj["i18n"].items()
            )
            if obj.get("i18n") is not None
            else None,
            "internal_id": obj.get("internal_id"),
            "is_public": obj.get("is_public"),
            "name": obj.get("name")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


