# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.29.5
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from aigentchat.models.ai_model_capability import AIModelCapability
from aigentchat.models.ai_model_constraint import AIModelConstraint
from aigentchat.models.execution_cost_template import ExecutionCostTemplate
from aigentchat.models.execution_usage_cost import ExecutionUsageCost
from typing import Optional, Set
from typing_extensions import Self

class AIModelFeature(BaseModel):
    """
    AIModelFeature
    """ # noqa: E501
    batch_cost_factor: Optional[Union[StrictFloat, StrictInt]] = None
    capability: Optional[AIModelCapability] = None
    constraints: Optional[List[AIModelConstraint]] = None
    cost_item_templates: Optional[List[ExecutionCostTemplate]] = None
    cost_items: Optional[List[ExecutionUsageCost]] = None
    long_context_threshold_tokens: Optional[StrictInt] = None
    non_default_hosting_location_cost_factor: Optional[Union[StrictFloat, StrictInt]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["batch_cost_factor", "capability", "constraints", "cost_item_templates", "cost_items", "long_context_threshold_tokens", "non_default_hosting_location_cost_factor"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AIModelFeature from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in constraints (list)
        _items = []
        if self.constraints:
            for _item_constraints in self.constraints:
                if _item_constraints:
                    _items.append(_item_constraints.to_dict())
            _dict['constraints'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cost_item_templates (list)
        _items = []
        if self.cost_item_templates:
            for _item_cost_item_templates in self.cost_item_templates:
                if _item_cost_item_templates:
                    _items.append(_item_cost_item_templates.to_dict())
            _dict['cost_item_templates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in cost_items (list)
        _items = []
        if self.cost_items:
            for _item_cost_items in self.cost_items:
                if _item_cost_items:
                    _items.append(_item_cost_items.to_dict())
            _dict['cost_items'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AIModelFeature from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "batch_cost_factor": obj.get("batch_cost_factor"),
            "capability": obj.get("capability"),
            "constraints": [AIModelConstraint.from_dict(_item) for _item in obj["constraints"]] if obj.get("constraints") is not None else None,
            "cost_item_templates": [ExecutionCostTemplate.from_dict(_item) for _item in obj["cost_item_templates"]] if obj.get("cost_item_templates") is not None else None,
            "cost_items": [ExecutionUsageCost.from_dict(_item) for _item in obj["cost_items"]] if obj.get("cost_items") is not None else None,
            "long_context_threshold_tokens": obj.get("long_context_threshold_tokens"),
            "non_default_hosting_location_cost_factor": obj.get("non_default_hosting_location_cost_factor")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


