# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.42.2
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AIModelCapability(str, Enum):
    """
    AIModelCapability
    """

    """
    allowed enum values
    """
    AIModelCapabilityNil = ''
    AIModelCapabilityFunctionCalling = 'function-calling'
    AIModelCapabilityFunctionCallingStreaming = 'function-calling_streaming'
    AIModelCapabilityTextToText = 'text-to-text'
    AIModelCapabilityTextToTextStreaming = 'text-to-text_streaming'
    AIModelCapabilitySpeechToText = 'speech-to-text'
    AIModelCapabilitySpeechToTextStreaming = 'speech-to-text_streaming'
    AIModelCapabilityImageToText = 'image-to-text'
    AIModelCapabilityPdfToText = 'pdf-to-text'
    AIModelCapabilityDocumentToText = 'document-to-text'
    AIModelCapabilityVideoToText = 'video-to-text'
    AIModelCapabilityVideoToTextStreaming = 'video-to-text_streaming'
    AIModelCapabilityTextToSpeech = 'text-to-speech'
    AIModelCapabilityTextToSpeechStreaming = 'text-to-speech_streaming'
    AIModelCapabilityTextToMusic = 'text-to-music'
    AIModelCapabilityTextToMusicStreaming = 'text-to-music_streaming'
    AIModelCapabilityTextToImage = 'text-to-image'
    AIModelCapabilityTextToVideo = 'text-to-video'
    AIModelCapabilityTextToVideoStreaming = 'text-to-video_streaming'
    AIModelCapabilityTextToEmbedding = 'text-to-embedding'
    AIModelCapabilitySpeechToEmbedding = 'speech-to-embedding'
    AIModelCapabilityImageToEmbedding = 'image-to-embedding'
    AIModelCapabilityVideoToEmbedding = 'video-to-embedding'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AIModelCapability from a JSON string"""
        return cls(json.loads(json_str))


