# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.25.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ApiErrorCode(str, Enum):
    """
    ApiErrorCode
    """

    """
    allowed enum values
    """
    ErrCodeNil = ''
    ErrCodePermissionDenied = 'permission_denied'
    ErrCodeUnknown = 'unknown'
    ErrCodeUnauthorized = 'unauthorized'
    ErrCodeInvalidPayload = 'invalid_payload'
    ErrCodeInvalidEntity = 'invalid_entity'
    ErrCodeInvalidParams = 'invalid_params'
    ErrCodeInvalidDate = 'invalid_date'
    ErrCodeStartDateMustBeBeforeEndDate = 'start_date_must_be_before_end_date'
    ErrCodeAgentNotFound = 'agent_not_found'
    ErrCodeInvalidAgentID = 'invalid_agent_id'
    ErrCodeFailedToCreateAgent = 'failed_to_create_agent'
    ErrCodeFailedToCreateDefaultAgents = 'failed_to_create_default_agents'
    ErrCodeFailedToDeleteAgent = 'failed_to_delete_agent'
    ErrCodeFailedToGetAgent = 'failed_to_get_agent'
    ErrCodeFailedToUpdateAgent = 'failed_to_update_agent'
    ErrCodeAIModelNotFound = 'ai_model_not_found'
    ErrCodeInvalidAIModelID = 'invalid_ai_model_id'
    ErrCodeInvalidAIModelDefinition = 'invalid_ai_model_definition'
    ErrCodeFailedToCreateAIModel = 'failed_to_create_ai_model'
    ErrCodeFailedToUpdateAIModel = 'failed_to_update_ai_model'
    ErrCodeFailedToDeleteAIModel = 'failed_to_delete_ai_model'
    ErrCodeFailedToFetchAIModel = 'failed_to_fetch_ai_model'
    ErrCodeInvalidAIModelServiceID = 'invalid_ai_model_service_id'
    ErrCodeAIModelServiceNotFound = 'ai_model_service_not_found'
    ErrCodeAIModelServiceActionNotAvailable = 'ai_model_service_action_not_available'
    ErrCodeFailedToCreateAIModelService = 'failed_to_create_ai_model_service'
    ErrCodeFailedToUpdateAIModelService = 'failed_to_update_ai_model_service'
    ErrCodeFailedToDeleteAIModelService = 'failed_to_delete_ai_model_service'
    ErrCodeFailedToFetchAIModelService = 'failed_to_fetch_ai_model_service'
    ErrCodeAIRegistryServiceNotEnabled = 'ai_registry_service_not_enabled'
    ErrCodeAIRegistryServiceLocationNotEnabled = 'ai_registry_service_location_not_enabled'
    ErrCodeAIRegistryFailedToGetService = 'ai_registry_failed_to_get_service'
    ErrCodeAIServiceAuthentication = 'ai_service_authentication'
    ErrCodeAIServiceBadRequest = 'ai_service_bad_request'
    ErrCodeAIServiceContentFilter = 'ai_service_content_filter'
    ErrCodeAIServiceInternalServerError = 'ai_service_internal_server_error'
    ErrCodeAIServiceOverload = 'ai_service_overload'
    ErrCodeAIServicePermissionDenied = 'ai_service_permission_denied'
    ErrCodeAIServiceRequestTooLarge = 'ai_service_request_too_large'
    ErrCodeAIServiceRateLimit = 'ai_service_rate_limit'
    ErrCodeAIServiceUnprocessableEntity = 'ai_service_unprocessable_entity'
    ErrCodeFailedToTranscribeAudio = 'failed_to_transcribe_audio'
    ErrCodeChannelNotFound = 'channel_not_found'
    ErrCodeInvalidChannelID = 'invalid_channel_id'
    ErrCodeFailedToCreateChannel = 'failed_to_create_channel'
    ErrCodeFailedToUpdateChannel = 'failed_to_update_channel'
    ErrCodeFailedToDeleteChannel = 'failed_to_delete_channel'
    ErrCodeFailedToFetchChannel = 'failed_to_fetch_channel'
    ErrCodeFailedToFetchChannels = 'failed_to_fetch_channels'
    ErrCodeFailedToFetchSubscribed = 'failed_to_fetch_subscribed_channels'
    ErrCodeFailedToCreateChatContext = 'failed_to_create_chat_context'
    ErrCodeCapabilityNotAvailable = 'capability_not_available'
    ErrCodeNoMessagesFound = 'no_messages_found'
    ErrCodeInvalidRequestParameters = 'invalid_request_parameters'
    ErrCodeChatCompletionTooManyTempFiles = 'chat_completion_too_many_temporary_files'
    ErrCodeChatCompletionExceedsTotalTempFileSize = 'chat_completion_exceeds_total_temporary_file_size'
    ErrCodeChatCompletionExceedsMaxInputTokens = 'chat_completion_exceeds_max_input_tokens'
    ErrCodeChatCompletionExceedsMaxToolCalls = 'chat_completion_exceeds_max_tool_calls'
    ErrCodeChatCompletionInProgress = 'chat_completion_in_progress'
    ErrCodeFailedToCreateConnectionToken = 'failed_to_create_connection_token'
    ErrCodeFailedToEmbedText = 'failed_to_embed_text'
    ErrCodeFailedToSearchExecutionLogs = 'failed_to_search_execution_logs'
    ErrCodeInvalidFileID = 'invalid_file_id'
    ErrCodeFileNotFound = 'file_not_found'
    ErrCodeFileUploadCategoryMismatch = 'file_upload_category_mismatch'
    ErrCodeFileMimetypeNotAccepted = 'file_mimetype_not_accepted'
    ErrCodeFunctionCallNotFound = 'functioncall_not_found'
    ErrCodeFailedToGenerateImage = 'failed_to_generate_image'
    ErrCodeFailedToGenerateImageCost = 'failed_to_generate_image_cost'
    ErrCodeInvalidImageID = 'invalid_image_id'
    ErrCodeImageNotFound = 'image_not_found'
    ErrCodeFailedToDeleteImage = 'failed_to_delete_image'
    ErrCodeFailedToGetImage = 'failed_to_get_image'
    ErrCodeFailedToSearchImages = 'failed_to_search_images'
    ErrCodeFailedToStoreImages = 'failed_to_store_images'
    ErrCodeInvalidMessageID = 'invalid_message_id'
    ErrCodeMessageNotFound = 'message_not_found'
    ErrCodeFailedToUpdateMessage = 'failed_to_update_message'
    ErrCodeFailedToDeleteMessage = 'failed_to_delete_message'
    ErrCodeFailedToFetchMessage = 'failed_to_fetch_message'
    ErrCodeFailedToSearchMessage = 'failed_to_search_messages'
    ErrCodeFailedToCreateMessage = 'failed_to_create_message'
    ErrCodeFailedToRetrieveChannelMessages = 'failed_to_retrieve_channel_messages'
    ErrCodeFailedToRetrieveMessagesFromList = 'failed_to_retrieve_messages_from_list'
    ErrCodeFailedToFormUserMessage = 'failed_to_form_user_message'
    ErrCodeInvalidOrgID = 'invalid_organization_id'
    ErrCodeOrgCostBudgetNotFound = 'organization_cost_budget_not_found'
    ErrCodeFailedToCreateBudget = 'failed_to_create_organization_cost_budget'
    ErrCodeFailedToUpdateBudget = 'failed_to_update_organization_cost_budget'
    ErrCodeFailedToGetOrgCostBudget = 'failed_to_get_organization_cost_budget'
    ErrCodeInsufficientBudget = 'insufficient_budget'
    ErrCodeOrgCostBudgetExists = 'organization_cost_budget_exists'
    ErrCodeTagNotFound = 'tag_not_found'
    ErrCodeInvalidTagID = 'invalid_tag_id'
    ErrCodeFailedToCreateTag = 'failed_to_create_tag'
    ErrCodeFailedToUpdateTag = 'failed_to_update_tag'
    ErrCodeFailedToDeleteTag = 'failed_to_delete_tag'
    ErrCodeFailedToFetchTag = 'failed_to_fetch_tag'
    ErrCodeFailedToFetchTags = 'failed_to_fetch_tags'
    ErrCodeInvalidToolID = 'invalid_tool_id'
    ErrCodeFailedToCreateTempApiKey = 'failed_to_create_temp_api_key'
    ErrCodeInvalidPromptID = 'invalid_prompt_id'
    ErrCodePromptNotFound = 'prompt_not_found'
    ErrCodeFailedToGetPrompt = 'failed_to_get_prompt'
    ErrCodeFailedToUpdatePrompt = 'failed_to_update_prompt'
    ErrCodeFailedToDeletePrompt = 'failed_to_delete_prompt'
    ErrCodeInvalidPromptData = 'invalid_prompt_data'
    ErrCodePromptAlreadyExists = 'prompt_already_exists'
    ErrCodeInvalidVersion = 'invalid_prompt_version'
    ErrCodeVariableNotFound = 'variable_not_found'
    ErrCodeInvalidVariableValue = 'invalid_variable_value'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ApiErrorCode from a JSON string"""
        return cls(json.loads(json_str))


