# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.35.1
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aigentchat.models.channel_context_window import ChannelContextWindow
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Channel(BaseModel):
    """
    Channel
    """ # noqa: E501
    context_window: Optional[ChannelContextWindow] = None
    created_at: Optional[StrictInt] = None
    description: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    is_org_public: Optional[StrictBool] = None
    is_public: Optional[StrictBool] = None
    last_message_at: Optional[StrictInt] = None
    metadata: Optional[Dict[str, Any]] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    owner_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    owner_organization_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    summary: Optional[Annotated[str, Field(strict=True, max_length=1024)]] = None
    type: Optional[StrictStr] = None
    updated_at: Optional[StrictInt] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["context_window", "created_at", "description", "id", "is_org_public", "is_public", "last_message_at", "metadata", "name", "owner_id", "owner_organization_id", "summary", "type", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Channel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of context_window
        if self.context_window:
            _dict['context_window'] = self.context_window.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Channel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "context_window": ChannelContextWindow.from_dict(obj["context_window"]) if obj.get("context_window") is not None else None,
            "created_at": obj.get("created_at"),
            "description": obj.get("description"),
            "id": obj.get("id"),
            "is_org_public": obj.get("is_org_public"),
            "is_public": obj.get("is_public"),
            "last_message_at": obj.get("last_message_at"),
            "metadata": obj.get("metadata"),
            "name": obj.get("name"),
            "owner_id": obj.get("owner_id"),
            "owner_organization_id": obj.get("owner_organization_id"),
            "summary": obj.get("summary"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


