# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.25.0
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FinishReason(str, Enum):
    """
    FinishReason
    """

    """
    allowed enum values
    """
    FinishReasonNil = ''
    FinishReasonError = 'error'
    FinishReasonContentFilter = 'content_filter'
    FinishReasonMaxTokens = 'max_tokens'
    FinishReasonStop = 'stop'
    FinishReasonToolCalls = 'tool_calls'
    FinishReasonDelta = 'delta'
    FinishReasonUnknown = 'unknown'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FinishReason from a JSON string"""
        return cls(json.loads(json_str))


