# coding: utf-8

"""
    vAudience AIgentChat API

    chat and api server for AIgents

    The version of the OpenAPI document: 0.25.2
    Contact: contact@vaudience.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from aigentchat.models.tag_i18n import TagI18n
from typing import Optional, Set
from typing_extensions import Self

class Tag(BaseModel):
    """
    Tag
    """ # noqa: E501
    created_at: Optional[StrictInt] = None
    i18n: Optional[Dict[str, TagI18n]] = None
    id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    internal_id: Optional[StrictStr] = None
    is_public: Optional[StrictBool] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=255)]
    organization_id: Annotated[str, Field(min_length=1, strict=True, max_length=64)]
    type: StrictStr
    updated_at: Optional[StrictInt] = None
    updated_by: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=64)]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["created_at", "i18n", "id", "internal_id", "is_public", "name", "organization_id", "type", "updated_at", "updated_by"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['agent', 'prompt']):
            raise ValueError("must be one of enum values ('agent', 'prompt')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Tag from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each value in i18n (dict)
        _field_dict = {}
        if self.i18n:
            for _key_i18n in self.i18n:
                if self.i18n[_key_i18n]:
                    _field_dict[_key_i18n] = self.i18n[_key_i18n].to_dict()
            _dict['i18n'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Tag from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "i18n": dict(
                (_k, TagI18n.from_dict(_v))
                for _k, _v in obj["i18n"].items()
            )
            if obj.get("i18n") is not None
            else None,
            "id": obj.get("id"),
            "internal_id": obj.get("internal_id"),
            "is_public": obj.get("is_public"),
            "name": obj.get("name"),
            "organization_id": obj.get("organization_id"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "updated_by": obj.get("updated_by")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


